// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvwDHeObgR52ZwVQG0QHKaj38zkBMyJA',
    appId: '1:392070178532:web:96c5b656b96bfa14722ef1',
    messagingSenderId: '392070178532',
    projectId: 'notification-89a5d',
    authDomain: 'notification-89a5d.firebaseapp.com',
    storageBucket: 'notification-89a5d.appspot.com',
    measurementId: 'G-1VK38L6E00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdtv06oj7dQBhudl-h3lnyFMdlLdlhL4',
    appId: '1:392070178532:android:1567125d12577f4a722ef1',
    messagingSenderId: '392070178532',
    projectId: 'notification-89a5d',
    storageBucket: 'notification-89a5d.appspot.com',
  );
}
